config/routes.rb
Rails.application.routes.draw do
  
  resources :events do
    resources :feedbacks, :controller => "event_feedbacks"
  end  

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :events
end

app/models/event.rb
class Event < ActiveRecord::Base
	validates_presence_of :name

	belongs_to :category
	has_many :feedbacks
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base

	belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/event_feedbacks_controller.rb
class EventFeedbacksController < ApplicationController

	before_action :set_event

	def index
		@feedbacks = @event.feedbacks
	end

	def show
		@feedback = @event.feedbacks.find( params[:id] )
	end

	def edit
		@feedback = @event.feedbacks.find( params[:id] )
	end

	def new
		@feedback = @event.feedbacks.build
	end

	def create
	  	@feedback = @event.feedbacks.build( feedback_params)

	  	if @feedback.save
	  		redirect_to event_feedbacks_path(@event)
	  	else
	  		render :action => "new"
	  	end
  	end

  	def destroy
	 
	  	@feedback = @event.feedbacks.find( params[:id] )
	  	@feedback.destroy

	  	redirect_to event_feedbacks_path(@event)
  	end

  	def update
	  	@feedback = @event.feedbacks.find( params[:id] )
	  	
	  	if @feedback.update( feedback_params )
	  		redirect_to event_feedbacks_path(@event)
	  	else
	  		render :action => "edit"
	  	end

  	end



	protected

	def set_event
		@event = Event.find( params[:event_id] )	
	end

	def feedback_params
  		params.require(:feedback).permit(:content, :name)
  	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_action :set_event, :only => [ :show, :edit, :update, :destroy]

	def index
  		@events = Event.order("id DESC").page(params[:page]).per(5)

  		if params[:event_id]
  			@event = Event.find( params[:event_id] )
  		else
			@event = Event.new
  		end

	end

	def show
  		
	end

	def new
  		@event = Event.new
	end

	def create
	  @event = Event.new(event_params)
	  if @event.save
	  	flash[:notice] = "event was successfully created"
	    redirect_to events_url
	  else
	    render :action => :new
	  end
	end

	def edit
  		
	end

	def update
	  if @event.update(event_params)
	  	flash[:notice] = "event was successfully updated"
	    redirect_to event_url(@event)
	  else
	    render :action => :edit
	  end
	end


	def destroy
  		@event.destroy
  		flash[:alert] = "event was successfully deleted"
  		redirect_to events_url
	end

	private

	def event_params
	  params.require(:event).permit(:name, :description, :content, :category_id)
	end

	def set_event
  		@event = Event.find(params[:id])
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_feedbacks_helper.rb
module EventFeedbacksHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/event_feedbacks/edit.html.erb
<h2>You Can Edit Your Feedback</h2>

<%= form_for @feedback, :url => event_feedback_path(@event, @feedback) do |f| %>

	<div class="form-group">
		<li>Feedback	<%= f.label :name %> </li>
		<%= f.text_field :name, :class => "form-control"%>
	</div>

	<div class="form-group">
		<li>Feedback	<%= f.label :content %> </li>
		<%= f.text_area :content, :class => "form-control"%>
	</div>

	<div class="form-group">
		<%= f.submit :class => "btn btn-primary" %>
	</div>

<% end %>

app/views/event_feedbacks/index.html.erb
<h1>This is Feedbacks board </h1>
<h2>Event-title:<%= @event.name%></h2>
<h2>Content: <%= @event.content %></h2>

<table class="table">	

<tr>
	<td>Feedbacks</td>
	<td>Control</td>

</tr>

<tr>
	<% @feedbacks.each do |fe|%>

	<td>
		<%= fe.content %>

	</td>

	<td>
	<%= link_to "Show", event_feedback_path(@event, fe), :class => "btn btn-primary"%>

	<%= link_to "Edit", edit_event_feedback_path(@event, fe), :class => "btn btn-default"%>

		<%= link_to "Delete", event_feedback_path(@event, fe), :method =>"delete", :data => { :confirm => "Sure?"}, :class => "btn btn-danger"%>
	
	</td>
</tr>

<%end%>
</table>


<%= link_to "New Feedback", new_event_feedback_path(@event),:class => "btn btn-primary"%>

<%= link_to "Events Index", events_path(@event),:class => "btn btn-primary"%>

app/views/event_feedbacks/new.html.erb
<%= form_for @feedback, :url => event_feedbacks_path(@event) do |f| %>

<div class="form-group">
	<%= f.label :name, "What's Your Name?"%>
	<%= f.text_field :name%>
</div>

<div class="form-group">
	<%= f.label :content, "Any Feedback?" %>
	<%= f.text_area :content%>
</div>

<div class="form-group">
	<%= f.submit :class =>"btn btn-primary"%>
</div>

	

<%end%>

app/views/event_feedbacks/show.html.erb
<h2><%= @event.name  %></h2>

    <p>
	hello, I am <%= @feedback.name%>
	</p>
	<p>
	this is my feedback,
	<%= @feedback.content %>
	</p>


<%= link_to "index", event_feedbacks_path(@event) %>

app/views/events/_form.html.erb
<% if @event.errors.any? %>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>

<div class="form-group">
 	<%= f.label :category_id, "Category" %>
    <%= f.select :category_id, Category.all.map{|x| [x.name, x.id]}, :class => "form-control" %>
</div>


<div class="form-group">
   	<%= f.label :name, "Title" %>
	<%= f.text_field :name, :class => "form-control" %>
</div>
	
<div class="form-group">
    	
    <%= f.label :content, "Content" %>

	<%= f.text_area :content, :class => "form-control"  %>
    	
</div>

app/views/events/edit.html.erb
<%= form_for @event, :url => event_path(@event) do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= f.submit "Update",:class => "btn btn-primary" %>
<% end %>

app/views/events/index.html.erb
<h1>Typhon Events</h1>





<table class="table">
<tr>
	<td>Title</td>
	<td>Post Time</td>
	<td>Feedback</td>
	<td>Control</td>

</tr>


<% @events.each do |e| %>
  <tr>
  	<td>
    <%= e.name %>
    |
    <%= e.category.try(:name) %>


    </td>



	<td>
	<%= e.created_at %>

	</td>

	<td>
		<%= link_to "Feedback", event_feedbacks_path(e), :class => "btn btn-primary" %>
	</td>

    <td>

		<%= link_to "Show", event_path(e), :class => "btn btn-primary" %>


		
		<%= link_to "Edit", events_path(:event_id => e), :class => "btn btn-default" %>
		
		<%= link_to 'Delete', event_path(e), :method => :delete,:data =>{:confirm =>"R U SURE???"}, :class => "btn btn-danger" %>


  	</td>
  </tr>
<% end %>
</table>

<hr>
<%= link_to 'New Event', events_path,:class => "btn btn-default" %> 





<%= paginate @events %>

<%= form_for @event do |f| %>
    
	<% if @event.errors.any? %>
      <ul>
          <% @event.errors.full_messages.each do |m| %>
            <li><%= m %></li>
        <% end %>
      </ul>
  <% end %>

	<%= render :partial => 'form', :locals => { :f => f } %>

    <%= f.submit "Submit",:class => "btn btn-primary" %>
<% end %>

app/views/events/info.html.erb
<%= @event.name%>

app/views/events/new.html.erb
<%= form_for @event, :url => events_path do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<p> Title:
<%= @event.name %>
</p>
<p>
category:<%= @event.category.try(:name) %>
</p>
<p>Content:
<%= simple_format(@event.content) %>
</p>
<p><%= link_to 'Back to index', events_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Event application" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<div class="row">
	<div class="col-md-12">
		<% if flash[:notice].present? %>
			<div class="alert alert-success" role="alert">
				<%= flash[:notice] %>
			</div>
		<% end %>

		<% if flash[:alert].present? %>
			<div class="alert alert-danger" role="alert">
				<%= flash[:alert] %>
			</div>
		<% end %>


		<%= yield %>
	</div>

	</div>

</div>

</body>
</html>